### ISSUE TITLE
Setup Continuous Integration

### ISSUE THREAD

**Issue by igortalent** [marcgardiner/zi-spa#10] opened 2018-08-27 06:45 UTC
It might be a good idea to setup continuous integration on the project.
The possible options we may consider are CircleCI or Travis.
And we may want to set up at least one basic testing - for example, linting test.

**Comment by marcgardiner** [comment] 2018-08-27 07:00
Okay, that is good idea. Both CircleCI and Travis CI will be integrated in next step.

**Comment by marcgardiner** [comment] 2018-09-15 10:46
@igortalent The issue is completely resolved with the PR #12 & #14.

**Closed as completed by marcgardiner** 2018-09-15 10:46 UTC
Labels: question
